In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [35]:
df = pd.DataFrame({'Gender' : ['Male','Female','Male','Female','Male','Female'] ,
                    'Region' :['East','West','South','North','Central','East'],
                    'Rented_Ownhose':['Rent','OwnHouse','Rent','OwnHouse','Rent','OwnHouse'],
                   'Occupration' : ['It Employee' , 'GOVT Officer' , 'Student_intern' , 'Doctor','Teacher','Salesman'],
                   'Education' : ['BTECH','Inter','PG','MBBS','phd','Undergraduate']
                     })


df

   Gender   Region Rented_Ownhose     Occupration      Education
0    Male     East           Rent     It Employee          BTECH
1  Female     West       OwnHouse    GOVT Officer          Inter
2    Male    South           Rent  Student_intern             PG
3  Female    North       OwnHouse          Doctor           MBBS
4    Male  Central           Rent         Teacher            phd
5  Female     East       OwnHouse        Salesman  Undergraduate

In [36]:
# Gender and region columns are nominal columns
# Rented_Ownhouse , Occupation and Education are Odinal columns

In [37]:
# use onehot encoding for Nominal columns
# use Odinal encoding for odinal columns

In [38]:
from sklearn.preprocessing import OneHotEncoder
one_hot_obj = OneHotEncoder(drop='first')

one_hot_obj.fit(df[['Gender','Region']])

result = one_hot_obj.transform(df[['Gender','Region']])

In [39]:
one_hot_obj.categories_

[array(['Female', 'Male'], dtype=object),
 array(['Central', 'East', 'North', 'South', 'West'], dtype=object)]

In [40]:
one_hot_obj.get_feature_names_out()

array(['Gender_Male', 'Region_East', 'Region_North', 'Region_South',
       'Region_West'], dtype=object)

In [41]:
result = result.toarray()
result

array([[1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [42]:
t = pd.DataFrame(data = result , columns=one_hot_obj.get_feature_names_out() , index = ['r1','r2','r3','r4','r5','r6'])
t

    Gender_Male  Region_East  Region_North  Region_South  Region_West
r1          1.0          1.0           0.0           0.0          0.0
r2          0.0          0.0           0.0           0.0          1.0
r3          1.0          0.0           0.0           1.0          0.0
r4          0.0          0.0           1.0           0.0          0.0
r5          1.0          0.0           0.0           0.0          0.0
r6          0.0          1.0           0.0           0.0          0.0

In [43]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [45]:
t.index

Index(['r1', 'r2', 'r3', 'r4', 'r5', 'r6'], dtype='object')

In [46]:
df.reset_index(drop=True , inplace=True)

In [47]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [48]:
t.reset_index(drop=True , inplace=True)

t.index

RangeIndex(start=0, stop=6, step=1)

In [49]:
df = pd.concat([df , t] ,axis=1)

df

,Gender,Region,Rented_Ownhose,Occupration,Education,Gender_Male,Region_East,Region_North,Region_South,Region_West
0,Male,East,Rent,It Employee,BTECH,1.0,1.0,0.0,0.0,0.0
1,Female,West,OwnHouse,GOVT Officer,Inter,0.0,0.0,0.0,0.0,1.0
2,Male,South,Rent,Student_intern,PG,1.0,0.0,0.0,1.0,0.0
3,Female,North,OwnHouse,Doctor,MBBS,0.0,0.0,1.0,0.0,0.0
4,Male,Central,Rent,Teacher,phd,1.0,0.0,0.0,0.0,0.0
5,Female,East,OwnHouse,Salesman,Undergraduate,0.0,1.0,0.0,0.0,0.0

In [50]:
df = df.drop(['Gender' , 'Region'] , axis = 1)
df

,Rented_Ownhose,Occupration,Education,Gender_Male,Region_East,Region_North,Region_South,Region_West
0,Rent,It Employee,BTECH,1.0,1.0,0.0,0.0,0.0
1,OwnHouse,GOVT Officer,Inter,0.0,0.0,0.0,0.0,1.0
2,Rent,Student_intern,PG,1.0,0.0,0.0,1.0,0.0
3,OwnHouse,Doctor,MBBS,0.0,0.0,1.0,0.0,0.0
4,Rent,Teacher,phd,1.0,0.0,0.0,0.0,0.0
5,OwnHouse,Salesman,Undergraduate,0.0,1.0,0.0,0.0,0.0

In [51]:
df.columns

Index(['Rented_Ownhose', 'Occupration', 'Education', 'Gender_Male',
       'Region_East', 'Region_North', 'Region_South', 'Region_West'],
      dtype='object')

In [52]:
# Odinal Technique

from sklearn.preprocessing import OrdinalEncoder
odinal_obj = OrdinalEncoder()

odinal_obj.fit(df[['Rented_Ownhose', 'Occupration', 'Education']])

result_1 = odinal_obj.transform(df[['Rented_Ownhose', 'Occupration', 'Education']])

result_1

array([[1., 2., 0.],
       [0., 1., 1.],
       [1., 4., 3.],
       [0., 0., 2.],
       [1., 5., 5.],
       [0., 3., 4.]])

In [53]:
odinal_obj.categories_

[array(['OwnHouse', 'Rent'], dtype=object),
 array(['Doctor', 'GOVT Officer', 'It Employee', 'Salesman',
        'Student_intern', 'Teacher'], dtype=object),
 array(['BTECH', 'Inter', 'MBBS', 'PG', 'Undergraduate', 'phd'],
       dtype=object)]

In [55]:
odinal_obj.get_feature_names_out() + '_res'

array(['Rented_Ownhose_res', 'Occupration_res', 'Education_res'],
      dtype=object)

In [56]:
p = pd.DataFrame(data = result_1 , columns=odinal_obj.get_feature_names_out() + '_res')
p

   Rented_Ownhose_res  Occupration_res  Education_res
0                 1.0              2.0            0.0
1                 0.0              1.0            1.0
2                 1.0              4.0            3.0
3                 0.0              0.0            2.0
4                 1.0              5.0            5.0
5                 0.0              3.0            4.0

In [57]:
df = pd.concat([df , p],axis=1)

In [58]:
df

,Rented_Ownhose,Occupration,Education,Gender_Male,Region_East,Region_North,Region_South,Region_West,Rented_Ownhose_res,Occupration_res,Education_res
0,Rent,It Employee,BTECH,1.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0
1,OwnHouse,GOVT Officer,Inter,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
2,Rent,Student_intern,PG,1.0,0.0,0.0,1.0,0.0,1.0,4.0,3.0
3,OwnHouse,Doctor,MBBS,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0
4,Rent,Teacher,phd,1.0,0.0,0.0,0.0,0.0,1.0,5.0,5.0
5,OwnHouse,Salesman,Undergraduate,0.0,1.0,0.0,0.0,0.0,0.0,3.0,4.0

In [59]:
df = df.drop(['Rented_Ownhose', 'Occupration', 'Education'],axis=1)
df

,Gender_Male,Region_East,Region_North,Region_South,Region_West,Rented_Ownhose_res,Occupration_res,Education_res
0,1.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0
1,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
2,1.0,0.0,0.0,1.0,0.0,1.0,4.0,3.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0
4,1.0,0.0,0.0,0.0,0.0,1.0,5.0,5.0
5,0.0,1.0,0.0,0.0,0.0,0.0,3.0,4.0